#!/home/tres/Code/Scribble/screnv/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'celery==3.0.21','console_scripts','celeryev'
__requires__ = 'celery'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('celery', 'console_scripts', 'celeryev')()
)
