import os

#STORAGE AUTH
STORENAME=os.environ.get("STORAGE_USER")
STOREPASSWORD=os.environ.get("STORAGE_PASSWORD")

USERNAME=os.environ.get("BROKER_USER")
PASSWORD=os.environ.get("BROKER_PASSWORD")
BROKER_HOST=os.environ.get("BROKER_HOST")
BROKER_PORT=os.environ.get("BROKER_PORT")
BROKER_VHOST=os.environ.get("BROKER_VHOST")
BROKER_PROTOCOL=os.environ.get("BROKER_PROTOCOL")
BROKER_URL = "%s://%s:%s@%s%s%s" %(BROKER_PROTOCOL, USERNAME, PASSWORD, HOST,PORT,VHOST)

BROKER_USE_SSL = os.environ.get("BROKER_USE_SSL")

#RESULT
BROKER_RESULT_PROTOCOL = os.environ.get("BROKER_RESULT_PROTOCOL")
CELERY_RESULT_BACKEND = "%s://%s:%s@%s%s%s" %(BROKER_RESULT_PROTOCOL, USERNAME, PASSWORD, BROKER_HOST,BROKER_PORT,BROKER_VHOST)
CELERY_RESULT_EXCHANGE = os.environ.get("CELERY_RESULT_EXCHANGE")
CELERY_RESULT_EXCHANGE_TYPE = os.environ.get("CELERY_RESULT_EXCHANGE_TYPE")
CELERY_RESULT_PERSISTENT = os.environ.get("CELERY_RESULT_PERSISTENT")
CELERY_RESULT_SERIALIZER = os.environ.get("CELERY_RESULT_SERIALIZER")
CELERY_TASK_RESULT_EXPIRES = os.environ.get("CELERY_TASK_RESULT_EXPIRES")
#TASK

CELERY_TASK_SERIALIZER = os.environ.get("CELERY_TASK_SERIALIZER")
CELERY_ACCEPT_CONTENT=os.environ.get("CELERY_ACCEPT_CONTENT").split(',')
CELERY_IMPORTS = os.environ.get('OPENSHIFT_CELERY_IMPORTS').split(',')

#CELERY ROUTES WILL BE DONE AT THE APP UPDATE LEVEL BECAUSE IT CAN EASILY CHANGE / BE AMMENDED
#CELERY_ROUTES = {'endpoint.tasks.process_house': {'queue': 'house_cruncher'}}

#MISC
CELERY_TIMEZONE = "Europe/Luxembourg"
CELERY_ENABLE_UTC = True


